name = "AoG_DocsDraft"
uuid = "f3c909be-0d17-478c-b644-3fe7d7e19b75"
version = "0.0.1"
authors = ["Eben60"]

[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
AlgebraOfGraphics = "0.11.9"
DataFrames = "1.8.1"
Unitful = "1.25.1"
WGLMakie = "0.13.7"
julia = "1.10"
